@rem Gradle wrapper script for Windows.
@rem Generated by IntelliJ Platform Plugin Template — do not edit by hand.
@if "%DEBUG%"=="" @echo off
@rem ##########################################################################
@rem  Gradle startup script for Windows
@rem ##########################################################################
@rem Set local scope for the variables with windows NT shell
if "%OS%"=="Windows_NT" setlocal

set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

@rem Resolve the location of the JVM to use.
set JAVACMD=java.exe
if defined JAVA_HOME (
    set JAVACMD=%JAVA_HOME%\bin\java.exe
)

@rem Find the Gradle wrapper jar.
set WRAPPER_JAR=%APP_HOME%gradle\wrapper\gradle-wrapper.jar
if not exist "%WRAPPER_JAR%" (
    echo ERROR: Gradle wrapper jar not found: %WRAPPER_JAR%
    exit /b 1
)

@rem Execute Gradle
"%JAVACMD%" ^
    "-Dorg.gradle.appname=%APP_BASE_NAME%" ^
    -classpath "%WRAPPER_JAR%" ^
    org.gradle.wrapper.GradleWrapperMain %*

:end
@rem Return the exit code of the subprocess.
if "%OS%"=="Windows_NT" endlocal
